const KEY='hangeoreum-v1';
const initialClock='2026-10-10T10:00:00';
const seed=()=>({clock:initialClock,tasks:[
 {id:'clean',title:'안방 대청소',note:'바닥에 있는 물건부터 정리하기',small:'바닥에 있는 물건 5개만 치우기',due:'2026-10-10T10:00',priority:'높음',repeat:'weekly',days:[6],status:'pending',snoozes:0,created:'2026-10-06T09:00'},
 {id:'water',title:'물 한 잔 마시기',note:'아침을 가볍게 시작해요.',small:'물 한 모금 마시기',due:'2026-10-10T08:00',priority:'보통',repeat:'daily',days:[],status:'completed',completed:'2026-10-10T08:12',snoozes:0,created:'2026-10-06T09:00'},
 {id:'book',title:'책 10페이지 읽기',note:'침대 옆에 둔 책을 펼쳐요.',small:'책 한 페이지 읽기',due:'2026-10-10T14:00',priority:'보통',repeat:'none',days:[],status:'pending',snoozes:0,created:'2026-10-06T09:00'},
 {id:'walk',title:'가볍게 산책하기',note:'집 근처 공원 한 바퀴',small:'운동화 신고 밖에 나가기',due:'2026-10-10T18:00',priority:'보통',repeat:'days',days:[0,6],status:'pending',snoozes:0,created:'2026-10-06T09:00'},
 {id:'laundry',title:'침구 세탁하기',note:'베개 커버와 이불 커버',small:'베개 커버만 세탁기에 넣기',due:'2026-10-11T11:00',priority:'낮음',repeat:'weekly',days:[0],status:'pending',snoozes:0,created:'2026-10-06T09:00'}],events:[{task:'water',type:'complete',at:'2026-10-10T08:12',minutes:0}],settings:{interval:30}});
let state;try{state=JSON.parse(localStorage.getItem(KEY))||seed()}catch{state=seed()}
let view='today',selected=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date(state.clock),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16),date=d=>local(new Date(d)).slice(0,10),time=d=>local(new Date(d)).slice(11,16);
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()},event=(t,type,minutes=0)=>state.events.push({task:t.id,type,at:state.clock,minutes});
const statusLabel=t=>({pending:'예정',progressing:'진행 중',paused:'보류',completed:'완료',skipped:'오늘 못함'}[t.status]);
function toast(s){showMessage(s)}
function nextDue(t){return followingDue(t,new Date(Math.max(new Date(t.scheduledDue||t.due),now())))}
function complete(t){completeWithUndo(t)}
function act(id,action,minutes){const t=state.tasks.find(t=>t.id===id);if(!t)return;if(action==='uncomplete'){reopenTask(t);$('#sheet').close();return}if(['completed','skipped'].includes(t.status))return;if(action==='complete')complete(t);if(action==='start'||action==='small'){t.status='progressing';t.started ||= state.clock;t.smallActive=action==='small';t.checkAt=local(new Date(now().getTime()+(action==='small'?5:state.settings.interval)*60000));event(t,'start');save();toast(action==='small'?'5분만 시작해요. 끝나면 다시 확인할게요.':'시작했어요. 진행 상태를 다시 확인할게요.')}if(action==='snooze'){t.status='paused';t.scheduledDue ||= t.due;if(t.snoozeDate!==date(state.clock))t.snoozes=0;t.snoozeDate=date(state.clock);t.snoozes++;t.due=local(new Date(now().getTime()+minutes*60000));event(t,'snooze',minutes);save();toast(`${minutes}분 뒤에 다시 알려드릴게요.`)}if(action==='skip'){t.status='skipped';event(t,'skip');spawnNext(t);save();toast('오늘은 쉬어가요. 다음 반복 일정은 유지해요.')}$('#sheet').close()}
const active=()=>state.tasks.filter(t=>['pending','paused','progressing'].includes(t.status));
function focusMarkup(t){if(!t)return `<section class="focus"><span class="tag">다음 일정까지</span><h2>지금 예정된 일이 없어요</h2><p class="sub">다음 일정은 아래에서 확인할 수 있어요.</p></section>`;let small=t.snoozes>=3&&t.snoozeDate===date(state.clock);return `<section class="focus"><span class="tag">${t.status==='progressing'?'진행 중':small?'작게 시작하기':'지금 할 일'}</span><h2>${esc(t.smallActive?t.small:t.title)}</h2><p class="sub">${t.status==='progressing'?'끝났다면 완료로 기록하세요.':small?`오늘 ${t.snoozes}번 미뤘어요. 5분만 해볼까요?`:t.status==='paused'?'아까 하기로 한 일이에요. 지금 가볍게 시작해볼까요?':esc(t.note)}</p><div class="actions">${t.status==='progressing'?`<button class="primary" data-act="complete" data-id="${t.id}">✓ 완료했어요</button><button class="quiet" data-detail="${t.id}">잠깐 보류</button>`:`<button class="primary" data-act="${small?'small':'start'}" data-id="${t.id}">${small?'5분 시작':'시작하기'}</button><button class="quiet" data-act="snooze" data-min="10" data-id="${t.id}">10분 미루기</button><button class="quiet" data-detail="${t.id}">다른 선택</button>`}</div>${small?`<p class="sub">작은 첫걸음: ${esc(t.small)}</p>`:''}</section>`}
function taskMarkup(t){return enhancedTaskMarkup(t)}
function stats(){const cutoff=now().getTime()-30*86400000,events=state.events.filter(e=>new Date(e.at).getTime()>=cutoff&&new Date(e.at)<=now()),registered=state.tasks.filter(t=>!t.isRuleSource&&new Date(t.created).getTime()>=cutoff),done=registered.filter(t=>t.status==='completed'),snoozes=events.filter(e=>e.type==='snooze'),hours=[0,0,0,0];events.filter(e=>e.type==='complete').forEach(e=>hours[Math.floor(new Date(e.at).getHours()/6)]++);return `<div class="stats">${[[registered.length,'등록한 할 일'],[done.length,'완료한 할 일'],[Math.round(done.length/(registered.length||1)*100)+'%','완료율 · 등록한 항목 기준'],[snoozes.length,'미룬 횟수'],[(snoozes.length?Math.round(snoozes.reduce((n,e)=>n+e.minutes,0)/snoozes.length):0)+'분','평균 미룬 시간']].map(([n,l])=>`<div class="stat"><div class="big-number">${n}</div><small>${l}</small></div>`).join('')}</div><section class="rail-card"><h2>자주 완료하는 시간대</h2>${hours.map((n,i)=>`<div class="bar-row"><span>${['새벽 00–06','오전 06–12','오후 12–18','저녁 18–24'][i]}</span><i style="width:${n/(Math.max(...hours)||1)*55}%"></i><span>${n}회</span></div>`).join('')}<p class="sub">완료 기록이 쌓이면 나에게 맞는 시간을 찾을 수 있어요.</p></section>`}
function detail(id){const t=resolveTask(id);if(!t)return;id=t.id;selected=id;$('#sheet').innerHTML=`<div class="modal-head"><span class="tag">${statusLabel(t)}</span><button class="quiet" data-close aria-label="닫기">✕</button></div><h1>${esc(t.title)}</h1><p class="sub">${esc(t.note)}</p><p class="sub">${date(t.due)} ${time(t.due)} · ${t.snoozes}번 미룸 · ${esc(repeatText(t))}${t.endDate?" · "+esc(t.endDate)+"까지":""}</p>${t.snoozes>=3&&t.snoozeDate===date(state.clock)&&!['completed','skipped'].includes(t.status)?`<section class="focus"><strong>5분이면 충분해요</strong><p>${esc(t.small)}</p><button class="primary" data-act="small" data-id="${id}">5분 시작</button></section>`:''}${!['completed','skipped'].includes(t.status)?`<div class="actions"><button class="primary" data-act="start" data-id="${id}">${t.status==='progressing'?'계속 진행 중':'지금 시작'}</button><button class="primary" data-act="complete" data-id="${id}">✓ 완료했어요</button></div><h2 class="snooze-heading">지금 어렵다면</h2><div class="actions snooze-grid">${[10,30,60].map(n=>`<button class="quiet" data-act="snooze" data-id="${id}" data-min="${n}">${n===60?'1시간':n+'분'} 뒤</button>`).join('')}<button class="quiet" data-act="snooze" data-id="${id}" data-min="${Math.max(60,Math.round((new Date(date(state.clock)+'T20:00')-now())/60000))}">오늘 나중에</button><button class="quiet" data-act="skip" data-id="${id}">이번 일정 건너뛰기</button></div>`:''}<div class="actions"><button class="quiet" data-edit="${id}">수정</button><button class="delete" data-delete="${id}">삭제</button></div>`;if(!$('#sheet').open)$('#sheet').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-detail]');if(!b)return;const d=b.dataset;if('undo'in d){undoCompletion();return}if(d.preset){applyRepeatPreset($('#editor'),d.preset);return}if(d.view){view=d.view;render()}
if(d.scope){summaryScope=d.scope;render()}if(d.mode){calendarMode=d.mode;render()}
if(d.day){chosenDay=d.day;const day=new Date(d.day+'T00:00');month=new Date(day.getFullYear(),day.getMonth(),1);render()}
if(d.month){if(calendarMode==='week'){const day=new Date(chosenDay+'T00:00');day.setDate(day.getDate()+Number(d.month)*7);chosenDay=date(day);month=new Date(day.getFullYear(),day.getMonth(),1)}else{month=new Date(month.getFullYear(),month.getMonth()+Number(d.month),1);chosenDay=date(month)}render()}
if('today'in d){chosenDay=date(state.clock);month=new Date(now().getFullYear(),now().getMonth(),1);render()}
if('add'in d)editor();if(d.detail)detail(d.detail);if(d.edit)editor(d.edit);if('close'in d)$('#sheet').close();if(d.act){const t=resolveTask(d.id);if(t)act(t.id,d.act,Number(d.min))}if(d.delete){$('#sheet').innerHTML=`<h2>이 할 일을 삭제할까요?</h2><p class="sub">반복 일정이면 같은 시리즈의 모든 항목과 앞으로의 반복을 삭제합니다. 과거 이벤트 기록은 유지됩니다.</p><div class="actions"><button class="delete" data-confirm-delete="${d.delete}">삭제</button><button class="quiet" data-close>취소</button></div>`}if(d.confirmDelete){const removed=state.tasks.find(t=>t.id===d.confirmDelete);state.tasks=state.tasks.filter(t=>(t.seriesId||t.id)!==(removed.seriesId||removed.id));save();$('#sheet').close()}if(d.advance){state.clock=local(new Date(now().getTime()+Number(d.advance)*60000));materializeDue();save()}if('next'in d){const dates=nextQueue().map(t=>new Date(t.status==='progressing'?t.checkAt:t.due)).filter(d=>d>now());state.clock=local(dates.length?new Date(Math.min(...dates)):new Date(now().getTime()+86400000));materializeDue();chosenDay=date(state.clock);month=new Date(now().getFullYear(),now().getMonth(),1);save()}if('reset'in d){$('#sheet').innerHTML='<h2>테스트 데이터를 초기화할까요?</h2><p>추가한 할 일과 기록이 삭제됩니다.</p><div class="actions"><button class="delete" data-confirm-reset>초기화</button><button class="quiet" data-close>취소</button></div>';$('#sheet').showModal()}if('confirmReset'in d){state=seed();state.tasks.forEach(t=>{t.seriesId=t.id;t.anchor=t.due;t.every=1});chosenDay=date(state.clock);month=new Date(now().getFullYear(),now().getMonth(),1);save();$('#sheet').close()}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-detail]'))detail(e.target.dataset.detail)});

