const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const elements=new Map();const doc={querySelector:s=>{if(!elements.has(s))elements.set(s,{innerHTML:'',style:{},close(){},addEventListener(){}});return elements.get(s)},addEventListener(){}};
const storage=new Map();const c=vm.createContext({document:doc,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},crypto:require('node:crypto').webcrypto,setTimeout:()=>{},console});
vm.runInContext(fs.readFileSync('recurrence.js','utf8'),c);vm.runInContext(fs.readFileSync('app.js','utf8'),c);const run=s=>vm.runInContext(s,c);
assert.equal(run('state.tasks.length'),5);
run("act('clean','snooze',10);state.clock='2026-10-10T10:10';act('clean','snooze',30);state.clock='2026-10-10T10:40';act('clean','snooze',60)");
assert.equal(run("state.tasks[0].snoozes"),3);assert.equal(run("time(state.tasks[0].due)"),'11:40');assert.ok(run("focusMarkup(state.tasks[0]).includes('5분 시작')"));
run("act('clean','small');");assert.equal(run("state.tasks[0].status"),'progressing');assert.equal(run("time(state.tasks[0].checkAt)"),'10:45');
run("act('clean','complete')");assert.equal(run("state.tasks[0].status"),'completed');assert.equal(run("state.tasks.filter(t=>t.title==='안방 대청소'&&t.status==='pending')[0].due"),'2026-10-17T10:00');
assert.equal(run("state.events.filter(e=>e.type==='snooze').length"),3);assert.ok(run("stats().includes('33분')"));
run("state.clock='2026-10-11T10:00';act('book','snooze',10);state.clock='2026-10-12T10:00';act('book','snooze',10)");assert.equal(run("state.tasks.find(t=>t.id==='book').snoozes"),1);
run("state.clock='2026-10-10T10:00';act('walk','complete')");assert.equal(run("state.tasks.filter(t=>t.title==='가볍게 산책하기'&&t.status==='pending')[0].due"),'2026-10-11T18:00');
assert.ok(storage.has('hangeoreum-v1'));
run("state=seed();state.tasks.forEach(t=>{t.seriesId=t.id;t.anchor=t.due});state.clock='2026-10-10T10:00'");
const projectionCount=run("occurrences('2026-10-10','2026-10-31').length");
run("resolveTask('virtual|clean|2026-10-24T10:00')");
assert.equal(run("occurrences('2026-10-10','2026-10-31').length"),projectionCount);
assert.equal(run("occurrences('2026-10-17','2026-10-17').filter(t=>t.title==='안방 대청소').length"),1);
run("state.tasks[0].endDate='2026-10-17'");
assert.equal(run("occurrences('2026-10-17','2026-10-17').filter(t=>t.title==='안방 대청소').length"),1);
run("state.tasks[0].endDate=null;act('book','start')");
assert.equal(run('nextQueue()[0].id'),'book');
run("state.clock='2026-10-11T08:00';materializeDue()");
assert.equal(run("active().filter(t=>t.title==='물 한 잔 마시기'&&t.due==='2026-10-11T08:00').length"),1);
run('materializeDue()');
assert.equal(run("active().filter(t=>t.title==='물 한 잔 마시기'&&t.due==='2026-10-11T08:00').length"),1);
console.log('PASS: snooze, goal reduction, start, completion, recurrence, day reset, statistics, persistence, future projection materialization, widget ranking');
run("state=seed();state.tasks.forEach(t=>{t.seriesId=t.id;t.anchor=t.due});act('clean','start');act('clean','complete');undoCompletion()");
assert.equal(run("state.tasks.find(t=>t.id==='clean').status"),'progressing');
assert.equal(run("state.events.filter(e=>e.task==='clean'&&e.type==='complete').length"),0);
assert.equal(run("state.tasks.filter(t=>t.id!=='clean'&&t.seriesId==='clean').length"),0);
run("state=seed();state.tasks.forEach(t=>{t.seriesId=t.id;t.anchor=t.due});const one=state.tasks[0];commitTaskEdit(one,{...one,title:'이번 주만 변경',due:'2026-10-11T10:00',scheduledDue:'2026-10-11T10:00',anchor:'2026-10-11T10:00'},'this')");
assert.equal(run("occurrences('2026-10-11','2026-10-11').filter(t=>t.title==='이번 주만 변경').length"),1);
assert.equal(run("occurrences('2026-10-17','2026-10-17').filter(t=>t.title==='안방 대청소').length"),1);
assert.equal(run("occurrences('2026-10-18','2026-10-18').filter(t=>t.title==='이번 주만 변경').length"),0);
run("state=seed();state.tasks.forEach(t=>{t.seriesId=t.id;t.anchor=t.due});const future=resolveTask('virtual|clean|2026-10-17T10:00');commitTaskEdit(future,{...future,title:'이후 모두 변경',due:'2026-10-18T12:00',scheduledDue:'2026-10-18T12:00',anchor:'2026-10-18T12:00',days:[0]},'future')");
assert.equal(run("occurrences('2026-10-10','2026-10-10').filter(t=>t.title==='안방 대청소').length"),1);
assert.equal(run("occurrences('2026-10-24','2026-10-24').filter(t=>t.title==='안방 대청소').length"),0);
assert.equal(run("occurrences('2026-10-25','2026-10-25').filter(t=>t.title==='이후 모두 변경').length"),1);
console.log('PASS: completion undo restores status/statistics and cancels duplicate child; single edit and future series split');
run("state=seed();state.tasks.forEach(t=>{t.seriesId=t.id;t.anchor=t.due});act('book','complete');state=JSON.parse(JSON.stringify(state));undoRecord=null;act('book','uncomplete')");
assert.equal(run("state.tasks.find(t=>t.id==='book').status"),'pending');
assert.equal(run("state.events.filter(e=>e.task==='book'&&e.type==='complete').length"),0);
assert.ok(run("taskMarkup(state.tasks.find(t=>t.id==='water')).includes('data-act=\"uncomplete\"')"));
run("act('water','uncomplete')");assert.equal(run("state.tasks.find(t=>t.id==='water').status"),'pending');
run("act('clean','start');act('clean','complete');state=JSON.parse(JSON.stringify(state));act('clean','uncomplete')");
assert.equal(run("state.tasks.find(t=>t.id==='clean').status"),'progressing');
assert.equal(run("state.tasks.filter(t=>t.id!=='clean'&&t.seriesId==='clean').length"),0);
console.log('PASS: completed checkbox toggles after reload, legacy completion reopens, recurring completion restores status without duplicate persisted child');


